on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  release:
    types: [published]
  workflow_dispatch:

name: pkgdown.yaml

permissions: read-all

jobs:
  pkgdown:
    runs-on: ubuntu-latest
    concurrency:
      group: pkgdown-${{ github.event_name != 'pull_request' || github.run_id }}
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Clean up old R packages
        run: rm -rf /home/runner/work/_temp/Library/*

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::pkgdown, local::.
          needs: recompute

      - name: Force reinstall cli
        run: |
          Rscript -e 'remove.packages("cli")'
          Rscript -e 'install.packages("cli", dependencies = TRUE)'

      - uses: r-lib/actions/setup-tinytex@v2

      - name: Build site
        run: |
          echo 'Configuring _pkgdown.yml...'
          echo "navbar:" > ./_pkgdown.yml
          echo "  structure:" >> ./_pkgdown.yml
          echo "    right:" >> ./_pkgdown.yml
          echo "      - 'GitHub'" >> ./_pkgdown.yml
          echo "      - 'Reference'" >> ./_pkgdown.yml
          echo "  links:" >> ./_pkgdown.yml
          echo "    - title: 'GitHub'" >> ./_pkgdown.yml
          echo "      href: 'https://github.com/rOpenGov/finna'" >> ./_pkgdown.yml
          echo "    - title: 'Reference'" >> ./_pkgdown.yml
          echo "      href: 'reference/index.html'" >> ./_pkgdown.yml
          echo "template:" >> ./_pkgdown.yml
          echo "  bootstrap: 5" >> ./_pkgdown.yml

          rm -rf docs/

          Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'

      - name: Deploy to GitHub pages 🚀
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          clean: false
          branch: gh-pages
          folder: docs
